### ISSUE TITLE
Error on list create: request error nvim_call_function: Invalid scroll size

### ISSUE THREAD

**Issue by khaitranhq** [voldikss/coc-floaterm#3] opened 2020-10-11 12:09 UTC
## Describe the bug

`[coc.nvim] Error on list create: request error nvim_call_function - Vim(set):E49: Invalid scroll size: scroll = 10`

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Install vim-floatterm, coc.nvim
- Run command `CocInstall coc-floaterm`
- Run `:FloatermNew` x 5 times to create 5 floaterm
- Run `:FloatermToggle` to hide all floaterm
- Run `CocList floaterm` and then show that error. I can't press any key except killing terminal to close Vim.
You can see more about my neovim configure here:  https://github.com/lioaslan/nvim

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/24852182/95672096-134b5180-0bc8-11eb-8e76-a3bee6ae5801.png)

**Comment by voldikss** [comment] 2020-10-12 14:15
Close as it's a duplicate of https://github.com/voldikss/vim-floaterm/issues/190

**Closed as completed by voldikss** 2020-10-12 14:15 UTC
Labels: bug

**Comment by sparkcanon** [comment] 2021-06-07 17:35
I found this to be an issue as well.

### Minimal vim:

```vim
set nocompatible
set runtimepath^=/pack/main/start/coc.nvim
set runtimepath^=/pack/main/start/vim-floaterm
filetype plugin indent on
syntax on
set hidden
```

### coc logs:

```vim
## versions

vim version: VIM - Vi IMproved 8.2 8022925
node version: v12.18.3
coc.nvim version: 0.0.80-509209a03f
coc.nvim directory: /Users/<user>/.vim/pack/main/start/coc.nvim
term: tmux
platform: darwin

## Log of coc.nvim

2021-06-07T18:29:02.148 INFO (pid:57719) [coc-git] - Looking for git in: git
2021-06-07T18:29:02.360 INFO (pid:57719) [plugin] - coc.nvim 0.0.80-509209a03f initialized with node: v12.18.3 after 312ms
2021-06-07T18:29:02.380 INFO (pid:57719) [watchman] - watchman watching project: /Users/<user>/.vim
2021-06-07T18:29:17.604 INFO (pid:57719) [attach] - receive notification: highlight []
2021-06-07T18:29:18.594 INFO (pid:57719) [attach] - receive notification: highlight []
2021-06-07T18:29:20.352 INFO (pid:57719) [attach] - receive notification: highlight []
2021-06-07T18:29:20.755 INFO (pid:57719) [attach] - receive notification: highlight []
2021-06-07T18:29:21.445 INFO (pid:57719) [attach] - receive notification: highlight []
2021-06-07T18:29:23.321 INFO (pid:57719) [attach] - receive notification: highlight []
2021-06-07T18:29:30.272 INFO (pid:57719) [attach] - receive notification: highlight []
2021-06-07T18:29:37.927 INFO (pid:57719) [attach] - receive notification: highlight []
2021-06-07T18:29:38.291 INFO (pid:57719) [attach] - receive notification: highlight []
2021-06-07T18:29:52.139 INFO (pid:57719) [attach] - receive request: listNames []
2021-06-07T18:29:52.762 INFO (pid:57719) [attach] - receive notification: openList [ 'floaterm' ]
2021-06-07T18:29:52.767 ERROR (pid:57719) [node-client] - request error on "nvim_call_function" [ 'getbufinfo', [ 2 ] ] ERROR Error
    at nM.request (/Users/<user>/.vim/pack/main/start/coc.nvim/build/index.js:20:34604)
    at nM.call (/Users/<user>/.vim/pack/main/start/coc.nvim/build/index.js:22:6260)
    at Floaterm.<anonymous> (/Users/<user>/.config/coc/extensions/node_modules/coc-floaterm/lib/index.js:140:49)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/<user>/.config/coc/extensions/node_modules/coc-floaterm/lib/index.js:100:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
2021-06-07T18:29:52.768 ERROR (pid:57719) [list-manager] - Error
    at nM.request (/Users/<user>/.vim/pack/main/start/coc.nvim/build/index.js:20:34604)
    at nM.call (/Users/<user>/.vim/pack/main/start/coc.nvim/build/index.js:22:6260)
    at Floaterm.<anonymous> (/Users/<user>/.config/coc/extensions/node_modules/coc-floaterm/lib/index.js:140:49)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/<user>/.config/coc/extensions/node_modules/coc-floaterm/lib/index.js:100:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
2021-06-07T18:30:30.972 INFO (pid:57719) [attach] - receive notification: showInfo []
```

### Screenshot:
![Screenshot 2021-06-07 at 18 30 05](https://user-images.githubusercontent.com/41004069/121063564-6492fb80-c7be-11eb-9f4d-c77c154f3998.png)
